### ISSUE TITLE
Trying Bonsaicss

### ISSUE THREAD

**Issue by maxbertinetti** [bonsaicss/bonsai.css#11]
Hi. 

I want to start using Bonsai but I have some problem:

```html
<div style="--fx --fd:row --jc:center --ai:center;"></div>

<div id="container"></div>
```
where:
```css
#container {
    display: flex;
    /* establish flex container */
    flex-direction: row;
    /* make main axis horizontal (default value) */
    justify-content: center;
    /* center items horizontally, in this case */
    align-items: center;
    /* center items vertically, in this case */
}
```
for my understanding must have the same meaning, but is not working.

Because an internal div with id="box" and style:
```css
.box {
     width: 300px;
     margin: 5px;
    text-align: center;
}
```
Is not centered horizontally with Bonsai

What I'm doing wrong?
