### ISSUE TITLE
--text-c on other elements

### ISSUE THREAD

**Issue by yvesh** [bonsaicss/bonsai.css#16]
Hey @ciar4n and @C-Lodder,

you can currently set the heading (h1-h6) color with the color class helpers (.white, .blue etc.), but not other elements. What do you think about extending the list slightly with some inline elements?

At least for me span / b / i  and maybe code / mark could make sense, for example `<span class="green">Green Text</span>`

```css
span, i, /*..*/ {
  color: var(--text-c, inherit);
}
```

Thank you!

**Comment by ciar4n** [comment]
Initially, I wanted to avoid having too many variables however in hindsight this is possibly unavoidable. How would you feel about applying color with the following (currently will not work on all elements)...

Inline with...

```html
<span style="--text-c: var(--custom)">Sample</span>
```

Or at a stylesheet level to all elements with...

```css
span {
  --text-c: var(--custom);
}
```
