### ISSUE TITLE
[Feature] Add class to unstyle default styling

### ISSUE THREAD

**Issue by ibn-akbar** [bonsaicss/bonsai.css#49]
Hi,

Every now and then there's need to add classes for unstyling elements.
Like this:
```css
.button-icon {
  border: unset;
  box-shadow: unset;
}
```
If we add support for `.unstyle` class there'll be no need to unset/override styles and it'll come handy.
For example:
```css
.button:not(.unstyle), button:not(.unstyle) {
  ...
}
```
