### ISSUE TITLE
[Issue] block-quote issues (collection)

### ISSUE THREAD

**Issue by yvesh** [bonsaicss/bonsai.css#53]
Some issues using the blockquote:

- [x] Currently block quote styles are not easily overridable ("only" by changing the border-left property, some --color helper would be nice).
- [x] Top and bottom padding is too much (half or 10px instead of 16px would be better) -> imho
- [x] Background color is fixed to #fff; (Is there any reason to set it at all?)
- [x] Maybe make it usable with size helper (--x), not sure

```css
blockquote {
  border-left: 4px solid var(--primary);
  background-color: #fff;
  margin: 1.5rem 0;
  padding: 1rem 1.5rem;
  font-style: italic;
}
```
