### ISSUE TITLE
Adding multiple utilities for a class

### ISSUE THREAD

**Issue by DomPatmore-SAE** [bonsaicss/bonsai.css#69]
Is it possible to add multiple utilities per class, for example:
```
.myClasss{
    --bg:blue;
    --p:1em;
}
```

**Comment by ciar4n** [comment]
Bonsai utilities are intended for inline use via the style attribute. I am not sure if there is a use case for your example. In such a case you would most likely define your properties as normal.

Eg. 

```css
.myClasss{
    background: blue;
    padding: 1em;
}
```
